//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 The CloudPilot AI Authors.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigration) DeepCopyInto(out *ClusterMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigration.
func (in *ClusterMigration) DeepCopy() *ClusterMigration {
	if in == nil {
		return nil
	}
	out := new(ClusterMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigrationList) DeepCopyInto(out *ClusterMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigrationList.
func (in *ClusterMigrationList) DeepCopy() *ClusterMigrationList {
	if in == nil {
		return nil
	}
	out := new(ClusterMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigrationSpec) DeepCopyInto(out *ClusterMigrationSpec) {
	*out = *in
	in.NodePoolConfig.DeepCopyInto(&out.NodePoolConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigrationSpec.
func (in *ClusterMigrationSpec) DeepCopy() *ClusterMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterMigrationStatus) DeepCopyInto(out *ClusterMigrationStatus) {
	*out = *in
	if in.PodErrors != nil {
		in, out := &in.PodErrors, &out.PodErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterMigrationStatus.
func (in *ClusterMigrationStatus) DeepCopy() *ClusterMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodError) DeepCopyInto(out *PodError) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodError.
func (in *PodError) DeepCopy() *PodError {
	if in == nil {
		return nil
	}
	out := new(PodError)
	in.DeepCopyInto(out)
	return out
}
